export const BASE_URL = "http://localhost:8080"; 
export const BOOK_BASE_URL = "/api/v1/books";
export const CATEGORY_BASE_URL = "/api/v1/categories";
export const ISSUANCE_BASE_URL = "/api/v1/issuances"; 
export const USERS_BASE_URL = "/api/v1/users"
export const CURRENT_USER = "/api/v1/currentUser";
export const USER_HISTORY_BASE_URL = "/api/v1/user";
export const DASHBOARD_COUNT_BASE_URL = "/api/v1/dashboard"
export const SIGNIN_BASE_URL ="/api/v1/signin" 